//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WebSimuladorRH
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBOrcamentoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBOrcamentoEntities object using the connection string found in the 'DBOrcamentoEntities' section of the application configuration file.
        /// </summary>
        public DBOrcamentoEntities() : base("name=DBOrcamentoEntities", "DBOrcamentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBOrcamentoEntities object.
        /// </summary>
        public DBOrcamentoEntities(string connectionString) : base(connectionString, "DBOrcamentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBOrcamentoEntities object.
        /// </summary>
        public DBOrcamentoEntities(EntityConnection connection) : base(connection, "DBOrcamentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cargos> Cargos
        {
            get
            {
                if ((_Cargos == null))
                {
                    _Cargos = base.CreateObjectSet<Cargos>("Cargos");
                }
                return _Cargos;
            }
        }
        private ObjectSet<Cargos> _Cargos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cargos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCargos(Cargos cargos)
        {
            base.AddObject("Cargos", cargos);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBOrcamentoModel", Name="Cargos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cargos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cargos object.
        /// </summary>
        /// <param name="id_Cargo">Initial value of the id_Cargo property.</param>
        public static Cargos CreateCargos(global::System.Int64 id_Cargo)
        {
            Cargos cargos = new Cargos();
            cargos.id_Cargo = id_Cargo;
            return cargos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_Cargo
        {
            get
            {
                return _id_Cargo;
            }
            set
            {
                if (_id_Cargo != value)
                {
                    Onid_CargoChanging(value);
                    ReportPropertyChanging("id_Cargo");
                    _id_Cargo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Cargo");
                    Onid_CargoChanged();
                }
            }
        }
        private global::System.Int64 _id_Cargo;
        partial void Onid_CargoChanging(global::System.Int64 value);
        partial void Onid_CargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RJ_FUNCAO
        {
            get
            {
                return _RJ_FUNCAO;
            }
            set
            {
                OnRJ_FUNCAOChanging(value);
                ReportPropertyChanging("RJ_FUNCAO");
                _RJ_FUNCAO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RJ_FUNCAO");
                OnRJ_FUNCAOChanged();
            }
        }
        private global::System.String _RJ_FUNCAO;
        partial void OnRJ_FUNCAOChanging(global::System.String value);
        partial void OnRJ_FUNCAOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RJ_DESC
        {
            get
            {
                return _RJ_DESC;
            }
            set
            {
                OnRJ_DESCChanging(value);
                ReportPropertyChanging("RJ_DESC");
                _RJ_DESC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RJ_DESC");
                OnRJ_DESCChanged();
            }
        }
        private global::System.String _RJ_DESC;
        partial void OnRJ_DESCChanging(global::System.String value);
        partial void OnRJ_DESCChanged();

        #endregion
    
    }

    #endregion
    
}
